version: '3.9'
services:
  php-apache:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8181:80
    volumes: 
      - ./:/var/www/html
      
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root1
      MARIADB_DATABASE: novos_titans
      MARIADB_USER: sam_user
      MARIADB_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8585:80
    environment:
      - PMA_ARBITRARY=1