version: '3.9'
services:
  php-apache:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8181:80
    volumes: 
      - ./:/var/www/html
      
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: novos_titans
      MYSQL_USER: sam_user
      MYSQL_PASSWORD: senha2
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8585:80
    environment:
      - PMA_ARBITRARY=1
